export const post = [
  {
    id: 'clh9c1xvk00006555ksjnofyb',
    title: 'Banking and data visualization',
    slug: 'banking-and-data-visualization',
    description: 'Exploring data visualization in JavaScript',
    content:
      '<p>Data visualization has become increasingly important to me since starting my career in industry. I started with basic tools like Microsoft Office and Google Docs, but have since graduated to more advanced tools like ggplot in R. However, as I build a finance app for fun, I find that the data visualization landscape in Javascript is vast and confusing.</p><p>Initially, I thought about using a pie chart to display amounts by category, but ultimately decided to build my own band chart. Drawing inspiration from a portfolio tutorial on HTML and CSS, I created two elements: a container element that represents 0-100% and a child container element that takes a coded width to correspond to the percentage skill I want to visualize.I found that by reshaping my data into data organized by category, I could display each category as a segment of a band-chart.</p><p>This chart is responsive and works at all viewpoints tested. I also decided to only display categories that are 10% or more, with the first three letters of the category, as I found that this displayed the most information with the least amount of clutter.</p><pre><code>import type { ReactNode } from \'react\'\n\nexport function BandContainer({ children }: { children: ReactNode }) {\n\nreturn (\n&lt;div className=\'relative inline-flex h-5 w-96 bg-black dark:bg-white\';\n\n{children}\n\n&lt;/div&gt;;\n\n)\n\n}</code></pre><p>Second, a child container element, a span, that would take in a coded width that would correspond to the % skill (0-100) that I wanted to visualize.</p><pre><code>export interface BandChartProps {\n\nbgFill: string\n\n// generated by chromajs scale\n\nitemWidth: number\n\n// percentage of total\n\ncategory: string\n\n}\n\nexport function BandChart({\n\nbgFill,\n\nitemWidth,\n\ncategory,\n\n}: BandChartProps) {\n\nreturn (\n\n&lt;span&gt;\n\nkey={category}\n\nclassName=\'flex h-5 flex-row items-center justify-center font-semibold\'\n\nstyle={{\n\nbackgroundColor: "{bgFill}",\n\nwidth: "{itemWidth}%"\n\n}}\n\n{/* only display if 10% or greater */}\n\n{itemWidth &gt; 9 ? \'\': &lt;p className=\'translate-y-4 space-between flex text-[8px]\'\n{category} {itemWidth} &lt;p&gt;}\n\n&lt;/span&gt;\n\n)\n\n}</code></pre><p></p><p></p><p>&lt;img src="<a target="_blank" rel="noopener noreferrer nofollow" href="https://remix-bucket.s3.us-east-2.amazonaws.com/Screenshot%202023-03-16%20at%202.41.48%20AM.png">https://remix-bucket.s3.us-east-2.amazonaws.com/Screenshot%202023-03-16%20at%202.41.48%20AM.png</a>"&gt;</p><p><a target="_blank" rel="noopener noreferrer nofollow" href="https://remix-bucket.s3.us-east-2.amazonaws.com/Screenshot%202023-03-16%20at%202.41.48%20AM.png&quot;><p></p><p>This">This</a> chart is responsive and works at all viewpoints tested but I am only displaying categories that are 10% or more. I found that this + the first 3 letters of the category displayed the most information with the least amount of ugliness.</p>',
    imageUrl:
      'https://res.cloudinary.com/dch-photo/image/upload/v1683217116/ysdowp2rw4lzzfbg15zp.png',
    featured: false,
    published: true,
    userId: 'clh7n2qsm0000jqg62z54fymz',
    createdAt: '2023-05-04T16:19:47.264Z',
    updatedAt: '2023-08-22T00:21:24.140Z',
    user: {
      id: 'clh7n2qsm0000jqg62z54fymz',
      username: 'Grayone',
      email: 'derickchoskinson@gmail.com',
      avatarUrl:
        'https://res.cloudinary.com/dch-photo/image/upload/v1681942247/etaaeiiliaxrf86kza0i.jpg',
      role: 'ADMIN'
    },
    likes: [
      {
        userId: 'clh7pg2rj000065b35wvqge8d',
        postId: 'clh9c1xvk00006555ksjnofyb',
        createdAt: '2023-08-22T00:24:09.947Z',
        updatedAt: '2023-08-22T00:24:09.947Z'
      },
      {
        userId: 'clh7n2qsm0000jqg62z54fymz',
        postId: 'clh9c1xvk00006555ksjnofyb',
        createdAt: '2023-08-22T03:35:54.305Z',
        updatedAt: '2023-08-22T03:35:54.305Z'
      }
    ],
    favorites: [
      {
        userId: 'clh7pg2rj000065b35wvqge8d',
        postId: 'clh9c1xvk00006555ksjnofyb'
      }
    ],
    categories: [
      {
        id: '71dcf44b-95d3-4a33-8c1f-f2bb7b40f276',
        label: 'React',
        value: 'React'
      },
      {
        id: '83f8816f-7ad3-48e0-a783-d652dc3f288e',
        label: 'Typescript',
        value: 'Typescript'
      },
      {
        id: '0e7b6da0-ec48-4791-8d4d-584e8bd93cb8',
        label: 'Remix',
        value: 'Remix'
      },
      {
        id: '80587ec3-4587-4662-89aa-c073e7b79961',
        label: 'Prisma',
        value: 'Prisma'
      },
      {
        id: 'e326d102-86de-4b71-b3fc-19028170f5de',
        label: 'TailwindCss',
        value: 'TailwindCss'
      },
      {
        id: '89534bd8-394e-42d2-beaf-bc51406499e3',
        label: 'Coding',
        value: 'Coding'
      }
    ],
    comments: [
      {
        id: 'e38a1336-2d73-49f0-b37f-a3956aa0626f',
        message: 'adfadfasfasdfasdfa',
        createdAt: '2023-05-05T04:51:52.220Z',
        updatedAt: '2023-05-05T04:51:52.220Z',
        createdBy: 'DerickH',
        userId: 'clh7pg2rj000065b35wvqge8d',
        postId: 'clh9c1xvk00006555ksjnofyb',
        parentId: 'f9f33e51-a5dd-434e-9b11-37a33df243f2',
        likes: [
          {
            userId: 'clh7pg2rj000065b35wvqge8d',
            commentId: 'e38a1336-2d73-49f0-b37f-a3956aa0626f',
            createdAt: '2023-05-05T04:51:58.323Z',
            updatedAt: '2023-05-05T04:51:58.323Z'
          }
        ],
        user: {
          id: 'clh7pg2rj000065b35wvqge8d',
          username: 'DerickH',
          email: 'iderick@gmail.com',
          avatarUrl:
            'https://res.cloudinary.com/dch-photo/image/upload/v1681939465/dhcxf2eqqrbvpnxmrqhb.jpg',
          role: 'ADMIN'
        },
        children: [],
        _count: {
          children: 0,
          likes: 1
        }
      },
      {
        id: 'b9e1b77a-cd68-45e7-a9da-19ff373930a9',
        message: 'adfsdfasdfasd',
        createdAt: '2023-05-05T04:45:56.864Z',
        updatedAt: '2023-05-05T04:45:56.864Z',
        createdBy: 'DerickH',
        userId: 'clh7pg2rj000065b35wvqge8d',
        postId: 'clh9c1xvk00006555ksjnofyb',
        parentId: 'f9f33e51-a5dd-434e-9b11-37a33df243f2',
        likes: [
          {
            userId: 'clh7pg2rj000065b35wvqge8d',
            commentId: 'b9e1b77a-cd68-45e7-a9da-19ff373930a9',
            createdAt: '2023-08-22T04:31:47.813Z',
            updatedAt: '2023-08-22T04:31:47.813Z'
          }
        ],
        user: {
          id: 'clh7pg2rj000065b35wvqge8d',
          username: 'DerickH',
          email: 'iderick@gmail.com',
          avatarUrl:
            'https://res.cloudinary.com/dch-photo/image/upload/v1681939465/dhcxf2eqqrbvpnxmrqhb.jpg',
          role: 'ADMIN'
        },
        children: [],
        _count: {
          children: 0,
          likes: 1
        }
      },
      {
        id: 'b72375d3-feff-4a0e-a4dd-389b6db1aa03',
        message: 'for you I mean',
        createdAt: '2023-05-05T04:10:21.054Z',
        updatedAt: '2023-05-05T04:10:21.054Z',
        createdBy: 'DerickH',
        userId: 'clh7pg2rj000065b35wvqge8d',
        postId: 'clh9c1xvk00006555ksjnofyb',
        parentId: null,
        likes: [
          {
            userId: 'clh7pg2rj000065b35wvqge8d',
            commentId: 'b72375d3-feff-4a0e-a4dd-389b6db1aa03',
            createdAt: '2023-05-05T04:12:33.311Z',
            updatedAt: '2023-05-05T04:12:33.311Z'
          }
        ],
        user: {
          id: 'clh7pg2rj000065b35wvqge8d',
          username: 'DerickH',
          email: 'iderick@gmail.com',
          avatarUrl:
            'https://res.cloudinary.com/dch-photo/image/upload/v1681939465/dhcxf2eqqrbvpnxmrqhb.jpg',
          role: 'ADMIN'
        },
        children: [
          {
            id: 'ecc933bd-5e18-4453-a368-4f0d8881d0f6',
            message: 'adfasdfasfsd',
            createdAt: '2023-05-05T04:10:27.365Z',
            updatedAt: '2023-05-05T04:10:27.365Z',
            createdBy: 'DerickH',
            userId: 'clh7pg2rj000065b35wvqge8d',
            postId: 'clh9c1xvk00006555ksjnofyb',
            parentId: 'b72375d3-feff-4a0e-a4dd-389b6db1aa03',
            user: {
              id: 'clh7pg2rj000065b35wvqge8d',
              username: 'DerickH',
              email: 'iderick@gmail.com',
              avatarUrl:
                'https://res.cloudinary.com/dch-photo/image/upload/v1681939465/dhcxf2eqqrbvpnxmrqhb.jpg'
            },
            children: [
              {
                id: '421fefae-3c09-4359-a981-fe95b5d211ab',
                message: 'reply to adfasdfasfsd',
                createdAt: '2023-08-22T05:39:20.524Z',
                updatedAt: '2023-08-22T05:39:20.524Z',
                createdBy: 'DerickH',
                userId: 'clh7pg2rj000065b35wvqge8d',
                postId: 'clh9c1xvk00006555ksjnofyb',
                parentId: 'ecc933bd-5e18-4453-a368-4f0d8881d0f6'
              }
            ],
            likes: []
          }
        ],
        _count: {
          children: 1,
          likes: 1
        }
      },
      {
        id: 'e636d6eb-9264-4995-9a66-441df0fb7843',
        message: 'dadfadsfasdfadsfasdfsd',
        createdAt: '2023-05-05T04:36:38.756Z',
        updatedAt: '2023-05-05T04:36:38.756Z',
        createdBy: 'DerickH',
        userId: 'clh7pg2rj000065b35wvqge8d',
        postId: 'clh9c1xvk00006555ksjnofyb',
        parentId: 'f9f33e51-a5dd-434e-9b11-37a33df243f2',
        likes: [],
        user: {
          id: 'clh7pg2rj000065b35wvqge8d',
          username: 'DerickH',
          email: 'iderick@gmail.com',
          avatarUrl:
            'https://res.cloudinary.com/dch-photo/image/upload/v1681939465/dhcxf2eqqrbvpnxmrqhb.jpg',
          role: 'ADMIN'
        },
        children: [],
        _count: {
          children: 0,
          likes: 0
        }
      },
      {
        id: '54dcff3b-2e1d-40dc-9f4d-38801ebe0176',
        message: 'adfadfasdfsd',
        createdAt: '2023-05-05T04:38:58.216Z',
        updatedAt: '2023-05-05T04:38:58.216Z',
        createdBy: 'DerickH',
        userId: 'clh7pg2rj000065b35wvqge8d',
        postId: 'clh9c1xvk00006555ksjnofyb',
        parentId: null,
        likes: [],
        user: {
          id: 'clh7pg2rj000065b35wvqge8d',
          username: 'DerickH',
          email: 'iderick@gmail.com',
          avatarUrl:
            'https://res.cloudinary.com/dch-photo/image/upload/v1681939465/dhcxf2eqqrbvpnxmrqhb.jpg',
          role: 'ADMIN'
        },
        children: [
          {
            id: '3d2f3212-b54c-462d-9765-b29baf2d8027',
            message: 'ererere',
            createdAt: '2023-05-05T04:39:10.690Z',
            updatedAt: '2023-05-05T04:39:10.690Z',
            createdBy: 'DerickH',
            userId: 'clh7pg2rj000065b35wvqge8d',
            postId: 'clh9c1xvk00006555ksjnofyb',
            parentId: '54dcff3b-2e1d-40dc-9f4d-38801ebe0176',
            user: {
              id: 'clh7pg2rj000065b35wvqge8d',
              username: 'DerickH',
              email: 'iderick@gmail.com',
              avatarUrl:
                'https://res.cloudinary.com/dch-photo/image/upload/v1681939465/dhcxf2eqqrbvpnxmrqhb.jpg'
            },
            children: [],
            likes: []
          }
        ],
        _count: {
          children: 1,
          likes: 0
        }
      },
      {
        id: 'f9f33e51-a5dd-434e-9b11-37a33df243f2',
        message: 'wowwow',
        createdAt: '2023-05-05T04:09:26.714Z',
        updatedAt: '2023-05-05T04:09:26.714Z',
        createdBy: 'DerickH',
        userId: 'clh7pg2rj000065b35wvqge8d',
        postId: 'clh9c1xvk00006555ksjnofyb',
        parentId: null,
        likes: [],
        user: {
          id: 'clh7pg2rj000065b35wvqge8d',
          username: 'DerickH',
          email: 'iderick@gmail.com',
          avatarUrl:
            'https://res.cloudinary.com/dch-photo/image/upload/v1681939465/dhcxf2eqqrbvpnxmrqhb.jpg',
          role: 'ADMIN'
        },
        children: [
          {
            id: 'e38a1336-2d73-49f0-b37f-a3956aa0626f',
            message: 'adfadfasfasdfasdfa',
            createdAt: '2023-05-05T04:51:52.220Z',
            updatedAt: '2023-05-05T04:51:52.220Z',
            createdBy: 'DerickH',
            userId: 'clh7pg2rj000065b35wvqge8d',
            postId: 'clh9c1xvk00006555ksjnofyb',
            parentId: 'f9f33e51-a5dd-434e-9b11-37a33df243f2',
            user: {
              id: 'clh7pg2rj000065b35wvqge8d',
              username: 'DerickH',
              email: 'iderick@gmail.com',
              avatarUrl:
                'https://res.cloudinary.com/dch-photo/image/upload/v1681939465/dhcxf2eqqrbvpnxmrqhb.jpg'
            },
            children: [],
            likes: [
              {
                userId: 'clh7pg2rj000065b35wvqge8d',
                commentId: 'e38a1336-2d73-49f0-b37f-a3956aa0626f',
                createdAt: '2023-05-05T04:51:58.323Z',
                updatedAt: '2023-05-05T04:51:58.323Z'
              }
            ]
          },
          {
            id: 'e636d6eb-9264-4995-9a66-441df0fb7843',
            message: 'dadfadsfasdfadsfasdfsd',
            createdAt: '2023-05-05T04:36:38.756Z',
            updatedAt: '2023-05-05T04:36:38.756Z',
            createdBy: 'DerickH',
            userId: 'clh7pg2rj000065b35wvqge8d',
            postId: 'clh9c1xvk00006555ksjnofyb',
            parentId: 'f9f33e51-a5dd-434e-9b11-37a33df243f2',
            user: {
              id: 'clh7pg2rj000065b35wvqge8d',
              username: 'DerickH',
              email: 'iderick@gmail.com',
              avatarUrl:
                'https://res.cloudinary.com/dch-photo/image/upload/v1681939465/dhcxf2eqqrbvpnxmrqhb.jpg'
            },
            children: [],
            likes: []
          },
          {
            id: 'b069df05-039d-4db9-bff0-6e50560d2bb1',
            message: 'hh',
            createdAt: '2023-05-05T04:40:58.339Z',
            updatedAt: '2023-05-05T04:40:58.339Z',
            createdBy: 'DerickH',
            userId: 'clh7pg2rj000065b35wvqge8d',
            postId: 'clh9c1xvk00006555ksjnofyb',
            parentId: 'f9f33e51-a5dd-434e-9b11-37a33df243f2',
            user: {
              id: 'clh7pg2rj000065b35wvqge8d',
              username: 'DerickH',
              email: 'iderick@gmail.com',
              avatarUrl:
                'https://res.cloudinary.com/dch-photo/image/upload/v1681939465/dhcxf2eqqrbvpnxmrqhb.jpg'
            },
            children: [],
            likes: []
          },
          {
            id: 'b9e1b77a-cd68-45e7-a9da-19ff373930a9',
            message: 'adfsdfasdfasd',
            createdAt: '2023-05-05T04:45:56.864Z',
            updatedAt: '2023-05-05T04:45:56.864Z',
            createdBy: 'DerickH',
            userId: 'clh7pg2rj000065b35wvqge8d',
            postId: 'clh9c1xvk00006555ksjnofyb',
            parentId: 'f9f33e51-a5dd-434e-9b11-37a33df243f2',
            user: {
              id: 'clh7pg2rj000065b35wvqge8d',
              username: 'DerickH',
              email: 'iderick@gmail.com',
              avatarUrl:
                'https://res.cloudinary.com/dch-photo/image/upload/v1681939465/dhcxf2eqqrbvpnxmrqhb.jpg'
            },
            children: [],
            likes: [
              {
                userId: 'clh7pg2rj000065b35wvqge8d',
                commentId: 'b9e1b77a-cd68-45e7-a9da-19ff373930a9',
                createdAt: '2023-08-22T04:31:47.813Z',
                updatedAt: '2023-08-22T04:31:47.813Z'
              }
            ]
          },
          {
            id: 'fd3a80d0-6e09-490e-83de-99851cda81bb',
            message: 'adfafasdfasdfasd',
            createdAt: '2023-05-05T04:51:33.452Z',
            updatedAt: '2023-05-05T04:51:33.452Z',
            createdBy: 'DerickH',
            userId: 'clh7pg2rj000065b35wvqge8d',
            postId: 'clh9c1xvk00006555ksjnofyb',
            parentId: 'f9f33e51-a5dd-434e-9b11-37a33df243f2',
            user: {
              id: 'clh7pg2rj000065b35wvqge8d',
              username: 'DerickH',
              email: 'iderick@gmail.com',
              avatarUrl:
                'https://res.cloudinary.com/dch-photo/image/upload/v1681939465/dhcxf2eqqrbvpnxmrqhb.jpg'
            },
            children: [],
            likes: []
          }
        ],
        _count: {
          children: 5,
          likes: 0
        }
      },
      {
        id: 'ecc933bd-5e18-4453-a368-4f0d8881d0f6',
        message: 'adfasdfasfsd',
        createdAt: '2023-05-05T04:10:27.365Z',
        updatedAt: '2023-05-05T04:10:27.365Z',
        createdBy: 'DerickH',
        userId: 'clh7pg2rj000065b35wvqge8d',
        postId: 'clh9c1xvk00006555ksjnofyb',
        parentId: 'b72375d3-feff-4a0e-a4dd-389b6db1aa03',
        likes: [],
        user: {
          id: 'clh7pg2rj000065b35wvqge8d',
          username: 'DerickH',
          email: 'iderick@gmail.com',
          avatarUrl:
            'https://res.cloudinary.com/dch-photo/image/upload/v1681939465/dhcxf2eqqrbvpnxmrqhb.jpg',
          role: 'ADMIN'
        },
        children: [
          {
            id: '421fefae-3c09-4359-a981-fe95b5d211ab',
            message: 'reply to adfasdfasfsd',
            createdAt: '2023-08-22T05:39:20.524Z',
            updatedAt: '2023-08-22T05:39:20.524Z',
            createdBy: 'DerickH',
            userId: 'clh7pg2rj000065b35wvqge8d',
            postId: 'clh9c1xvk00006555ksjnofyb',
            parentId: 'ecc933bd-5e18-4453-a368-4f0d8881d0f6',
            user: {
              id: 'clh7pg2rj000065b35wvqge8d',
              username: 'DerickH',
              email: 'iderick@gmail.com',
              avatarUrl:
                'https://res.cloudinary.com/dch-photo/image/upload/v1681939465/dhcxf2eqqrbvpnxmrqhb.jpg'
            },
            children: [],
            likes: []
          }
        ],
        _count: {
          children: 1,
          likes: 0
        }
      },
      {
        id: 'fd3a80d0-6e09-490e-83de-99851cda81bb',
        message: 'adfafasdfasdfasd',
        createdAt: '2023-05-05T04:51:33.452Z',
        updatedAt: '2023-05-05T04:51:33.452Z',
        createdBy: 'DerickH',
        userId: 'clh7pg2rj000065b35wvqge8d',
        postId: 'clh9c1xvk00006555ksjnofyb',
        parentId: 'f9f33e51-a5dd-434e-9b11-37a33df243f2',
        likes: [],
        user: {
          id: 'clh7pg2rj000065b35wvqge8d',
          username: 'DerickH',
          email: 'iderick@gmail.com',
          avatarUrl:
            'https://res.cloudinary.com/dch-photo/image/upload/v1681939465/dhcxf2eqqrbvpnxmrqhb.jpg',
          role: 'ADMIN'
        },
        children: [],
        _count: {
          children: 0,
          likes: 0
        }
      },
      {
        id: '421fefae-3c09-4359-a981-fe95b5d211ab',
        message: 'reply to adfasdfasfsd',
        createdAt: '2023-08-22T05:39:20.524Z',
        updatedAt: '2023-08-22T05:39:20.524Z',
        createdBy: 'DerickH',
        userId: 'clh7pg2rj000065b35wvqge8d',
        postId: 'clh9c1xvk00006555ksjnofyb',
        parentId: 'ecc933bd-5e18-4453-a368-4f0d8881d0f6',
        likes: [],
        user: {
          id: 'clh7pg2rj000065b35wvqge8d',
          username: 'DerickH',
          email: 'iderick@gmail.com',
          avatarUrl:
            'https://res.cloudinary.com/dch-photo/image/upload/v1681939465/dhcxf2eqqrbvpnxmrqhb.jpg',
          role: 'ADMIN'
        },
        children: [],
        _count: {
          children: 0,
          likes: 0
        }
      },
      {
        id: '3d2f3212-b54c-462d-9765-b29baf2d8027',
        message: 'ererere',
        createdAt: '2023-05-05T04:39:10.690Z',
        updatedAt: '2023-05-05T04:39:10.690Z',
        createdBy: 'DerickH',
        userId: 'clh7pg2rj000065b35wvqge8d',
        postId: 'clh9c1xvk00006555ksjnofyb',
        parentId: '54dcff3b-2e1d-40dc-9f4d-38801ebe0176',
        likes: [],
        user: {
          id: 'clh7pg2rj000065b35wvqge8d',
          username: 'DerickH',
          email: 'iderick@gmail.com',
          avatarUrl:
            'https://res.cloudinary.com/dch-photo/image/upload/v1681939465/dhcxf2eqqrbvpnxmrqhb.jpg',
          role: 'ADMIN'
        },
        children: [],
        _count: {
          children: 0,
          likes: 0
        }
      },
      {
        id: 'b069df05-039d-4db9-bff0-6e50560d2bb1',
        message: 'hh',
        createdAt: '2023-05-05T04:40:58.339Z',
        updatedAt: '2023-05-05T04:40:58.339Z',
        createdBy: 'DerickH',
        userId: 'clh7pg2rj000065b35wvqge8d',
        postId: 'clh9c1xvk00006555ksjnofyb',
        parentId: 'f9f33e51-a5dd-434e-9b11-37a33df243f2',
        likes: [],
        user: {
          id: 'clh7pg2rj000065b35wvqge8d',
          username: 'DerickH',
          email: 'iderick@gmail.com',
          avatarUrl:
            'https://res.cloudinary.com/dch-photo/image/upload/v1681939465/dhcxf2eqqrbvpnxmrqhb.jpg',
          role: 'ADMIN'
        },
        children: [],
        _count: {
          children: 0,
          likes: 0
        }
      }
    ],
    _count: {
      comments: 11,
      likes: 2,
      favorites: 1
    }
  }
]
